Models/Food.cs
namespace FoodShop.Models
{
	public class Food
	{
        public int FoodID { get; set; }
        public string FoodName { get; set; }
        public string ShortDescription { get; set; }
        public double Price { get; set; }
        public string ImageURL { get; set; }
        public int Stock { get; set; }

        public int CategoryID { get; set; }
        public virtual Category Category { get; set; }
    }
}

Controllers/FoodController.cs
using FoodShop.Models;
using FoodShop.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using X.PagedList.Extensions;

namespace FoodShop.Controllers
{
	public class FoodController : Controller
	{
		FoodRepository foodRepository = new FoodRepository();

		Context c = new Context();
		public IActionResult Index(int page = 1)
		{
			return View(foodRepository.TList("Category").ToPagedList(page,3));
		}
		[HttpGet]
		public IActionResult FoodAdd()
		{
			List<SelectListItem> values=(from x in c.Categories.ToList()
										 select new SelectListItem
										 {
											 Text=x.CategoryName,
											 Value=x.CategoryID.ToString()
										 }).ToList();
			ViewBag.v1 = values;
			return View();
		}
		[HttpPost]
		public IActionResult FoodAdd(AddProduct p)
		{
			Food f = new Food();
			if(p.ImageURL != null)
			{
				var extension = Path.GetExtension(p.ImageURL.FileName);
				var newImageName = Guid.NewGuid() +extension;
				var location = Path.Combine(Directory.GetCurrentDirectory(),"wwwroot/Images/", newImageName);
				var stream = new FileStream(location, FileMode.Create);
				p.ImageURL.CopyTo(stream);
				f.ImageURL = newImageName;
			} 
			f.FoodName = p.Name;
			f.Price = p.Price;
			f.Stock = p.Stock;
			f.CategoryID = p.CategoryID;
			f.ShortDescription = p.ShortDescription;
			foodRepository.TAdd(f);
			return RedirectToAction("Index");
		}
		public IActionResult FoodDelete(int id)
		{
			foodRepository.TDelete(new Food { FoodID = id });
			return RedirectToAction("Index");
		}
		public IActionResult FoodGet(int id)
		{
			var x = foodRepository.TGet(id);
			List<SelectListItem> values = (from y in c.Categories.ToList()
										   select new SelectListItem
										   {
											   Text = y.CategoryName,
											   Value = y.CategoryID.ToString()
										   }).ToList();
			ViewBag.v1 = values;
			Food f = new Food()
			{
				CategoryID = x.CategoryID,
				FoodID = x.FoodID,
				FoodName = x.FoodName,
				Price = x.Price,
				Stock = x.Stock,
				ImageURL = x.ImageURL,
				ShortDescription = x.ShortDescription,
			};
			return View(f);
		}
		public IActionResult FoodUpdate(Food p)
		{
			var x = foodRepository.TGet(p.FoodID);
			x.FoodName = p.FoodName;
			x.ShortDescription = p.ShortDescription;
			x.Price = p.Price;
			x.ImageURL = p.ImageURL;
			x.Stock = p.Stock;
			x.CategoryID = p.CategoryID;
			foodRepository.TUpdate(x);
			return RedirectToAction("Index");
		}
	}
}

Views/Food/FoodAdd.cshtml
@model FoodShop.Models.AddProduct

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Food Adding Page</h2>
<br />
<form class="form-group" action="FoodAdd" asp-controller="Food" method="post" enctype="multipart/form-data">
    @Html.LabelFor(x => x.Name)
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.ShortDescription)
    @Html.TextBoxFor(x => x.ShortDescription, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Price)
    @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.ImageURL)
    //@Html.TextBoxFor(x => x.ImageURL, new { @class = "form-control" })
    <input type="file" name="ImageURL"/>
    <br />
    @Html.LabelFor(x => x.CategoryID)
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.v1, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Stock)
    @Html.TextBoxFor(x => x.Stock, new { @class = "form-control" })
    <br />
    <br />
    <button class="btn btn-info">Save</button>
</form>

Views/Food/FoodGet.cshtml
@using FoodShop.Models
@model Food

@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Food Updating Page</h2>
<br />
@using (Html.BeginForm("FoodUpdate", "Food", FormMethod.Post))
{
	@Html.Label("Food ID")
	@Html.TextBoxFor(x => x.FoodID, new { @class = "form-control" })
	<br />
	@Html.Label("Food Name")
	@Html.TextBoxFor(x => x.FoodName, new { @class = "form-control" })
	<br />
	@Html.Label("Description")
	@Html.TextBoxFor(x => x.ShortDescription, new { @class = "form-control" })
	<br />
	@Html.Label("Price")
	@Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
	<br />
	@Html.Label("Image URL")
	@Html.TextBoxFor(x => x.ImageURL, new { @class = "form-control" })
	<br />
	@Html.Label("Stock")
	@Html.TextBoxFor(x => x.Stock, new { @class = "form-control" })
	<br />
	@Html.Label("Category")
	/*@Html.TextBoxFor(x => x.CategoryID, new { @class = "form-control" }) */
	@Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.v1, new
		{
			@class =
				"form-control"
		})
	<br />
	<button class="btn btn-info">Save</button>
}

Views/Food/Index.cshtml
@using X.PagedList;
@using FoodShop.Models;
@using X.Web.PagedList
@model IPagedList<Food>
@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Food List</h2>
<br />
<table class="table table-bordered">
	<tr>
		<th>ID</th>
		<th>Food Name</th>
		<th>Price</th>
		<th>Stock</th>
		<th>Category Name</th>
		<th>Delete</th>
		<th>Update</th>
		<th>Details</th>
	</tr>
	@foreach (var x in Model)
	{
		<tr>
			<th>@x.FoodID</th>
			<td>@x.FoodName</td>
			<td>@x.Price</td>
			<td>@x.Stock</td>
			<td>@x.Category.CategoryName</td>
			<td><a href="/Food/FoodDelete/@x.FoodID/" class="btn btn-danger">Delete</a></td>
			<td><a href="/Food/FoodGet/@x.FoodID" class="btn btn-success">Update</a></td>
			<td><a href="#" class="btn btn-info">Details</a></td>
		</tr>
	}
</table>
@Html.PagedListPager((IPagedList)Model,page=>Url.Action("Index",new { page }))
<a href="/Food/FoodAdd/" class="btn btn-primary">New Food</a>