Controllers/ChartController.cs
using FoodShop.Models;
using FoodShop.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace FoodShop.Controllers
{
	public class ChartController : Controller
	{
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Index2()
        {
            return View();
        }
        public IActionResult VisualizeProductResult()
        {
            Context context = new Context();
            return Json(context.Foods.ToList());
        }
        public List<Class1> FoodList()
        {
            List<Class1> cs2 = new List<Class1>();
            FoodRepository f = new FoodRepository();

            cs2 = f.TList().Select(x => new Class1()
            {
                foodname = x.FoodName,
                stock = x.Stock
            }).ToList();
            return cs2;
        }

        public IActionResult Statistics()
        {
            Context context = new Context();

            var value1 = context.Foods.Count();
            ViewBag.v1 = value1;

			var value2 = context.Categories.Count();
			ViewBag.v2 = value2;

            var foid = context.Categories.Where(x => x.CategoryName == "Fruits").Select(y => 
                y.CategoryID).FirstOrDefault();
            ViewBag.d = foid;
            var value3 = context.Foods.Where(x=> x.CategoryID == foid).Count();
            ViewBag.v3 = value3;

            var value4 = context.Foods.Where(x => x.CategoryID == context.Categories.Where(z => z.CategoryName == 
            "Vegetables").Select(y => y.CategoryID).FirstOrDefault()).Count();
            ViewBag.v4 = value4;

            var value5 = context.Foods.Sum(x=>x.Stock);
            ViewBag.v5 = value5;

            var value6 = context.Foods.Where(x=> x.CategoryID==context.Categories.Where(y=> y.CategoryName ==
            "Legumes").Select(z=>z.CategoryID).FirstOrDefault()).Count();
            ViewBag.v6 = value6;

            var value7 = context.Foods.OrderByDescending(x => x.Stock).Select(y =>
            y.FoodName).FirstOrDefault();
            ViewBag.v7 = value7;

            var value8 = context.Foods.OrderBy(x => x.Stock).Select(y =>
            y.FoodName).FirstOrDefault();
            ViewBag.v8 = value8;

            var value9 = context.Foods.Average(x => x.Price).ToString("0.00");
            ViewBag.v9 = value9;

            var value10 = context.Categories.Where(x => x.CategoryName == "Fruits").Select(y =>
            y.CategoryID).FirstOrDefault();
            var value10p = context.Foods.Where(y => y.CategoryID == value10).Sum(x => x.Stock);
            ViewBag.v10 = value10p;

            var value11 = context.Categories.Where(x => x.CategoryName == "Vegetables").Select(y =>
            y.CategoryID).FirstOrDefault();
            var value11p = context.Foods.Where(y => y.CategoryID == value11).Sum(x => x.Stock);
            ViewBag.v11 = value11p;

            var value12 = context.Foods.OrderByDescending(x => x.Price).Select(y =>
            y.FoodName).FirstOrDefault();
            ViewBag.v12 = value12;

            return View();
        }
    }
}

Views/Chart/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<html lang="en">
<head>
    <title>Result Visualization</title>
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeProductResult", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stocks');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.foodname, obj.stock]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Product - Stock Chart",
                width: 1000,
                height: 500,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.PieChart(document
                .getElementById('Piechart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>
</body>
</html>

Views/Chart/Index2.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeProductResult", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stocks');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.foodname, obj.stock]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Product - Stock Chart",
                width: 1000,
                height: 500,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.ColumnChart(document
                .getElementById('columnChart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="columnChart_div"></div>
</body>
</html>

Views/Chart/Statistics.cshtml
@{
    ViewData["Title"] = "Deneme";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!DOCTYPE html>
<html>
<head>
	<link href="~/coretemplateweb2-master/coretemplateweb2-master/css/bootstrap.css" rel="stylesheet" />
	<link href="~/coretemplateweb2-master/coretemplateweb2-master/css/clndr.css" rel="stylesheet" />
	<link href="~/coretemplateweb2-master/coretemplateweb2-master/css/jqvmap.css" rel="stylesheet" />
	<link href="~/coretemplateweb2-master/coretemplateweb2-master/css/style.css" rel="stylesheet" />
    <!-- Custom Theme files -->
    <link href="~/web2/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- Custom Theme files -->
    <script src="~/web2/js/jquery.min.js"></script>
    <link rel="stylesheet" href="~/web2/css/font-awesome.css">
    <!-- Custom Theme files -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Metro Panel Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--webfont-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <link href="~/web2/css/jqvmap.css" media="screen" rel="stylesheet" type="text/css" />


    <script src="~/web2/js/easyResponsiveTabs.js" type="text/javascript"></script>

    <script src="~/web2/js/main.js"></script> <!-- Resource jQuery -->
    <!-- chart -->
    <script src="~/web2/js/Chart1.js"></script>
    <!-- //chart -->
</head>
<body>
    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#1abc9c">
                <div class="icon-text">
                    <h3>@ViewBag.v1</h3>
                    <p>Total Food</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#2ecc71">

                <div class="icon-text">
                    <h3>@ViewBag.v2</h3>
                    <p>Total Category</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#3498db">

                <div class="icon-text">
                    <h3>@ViewBag.v3</h3>
                    <p>Fruit Count</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#9b59b6">

                <div class="icon-text">
                    <h3>@ViewBag.v4</h3>
                    <p>Vegetable Count</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#f39c12">
                <div class="icon-text">
                    <h3>@ViewBag.v6</h3>
                    <p>Legumes Count</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#d35400">
                <div class="icon-text">
                    <h3>@ViewBag.v5</h3>
                    <p>Sum Food</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#c0392b">

                <div class="icon-text">
                    <h3>@ViewBag.v7</h3>
                    <p>Max Stocked Food</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#7f8c8d">

                <div class="icon-text">
                    <h3>@ViewBag.v8</h3>
                    <p>Min Stocked Food</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#01a3a4">
                <div class="icon-text">
                    <h3>@ViewBag.v9€</h3>
                    <p>Average Food Price</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#ffb142">

                <div class="icon-text">
                    <h3>@ViewBag.v10</h3>
                    <p>Sum Fruit</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#40407a">

                <div class="icon-text">
                    <h3>@ViewBag.v11</h3>
                    <p>Sum Vegetables</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#4b4b4b">

                <div class="icon-text">
                    <h3>@ViewBag.v12</h3>
                    <p>Max Priced Food</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <div class="clearfix"></div>
</body>
</html>